name: tugas3
description: "pixel quest"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  rive: ^0.13.13
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
